# Generated by Django 2.2 on 2021-11-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tone', '0002_auto_20211118_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudak',
            name='resource_group_id',
            field=models.CharField(blank=True, help_text='资源组ID', max_length=32, null=True),
        ),
    ]
