# Generated by Django 2.2 on 2021-12-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tone', '0003_cloudak_resource_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outsitemsg',
            name='cc_to',
            field=models.TextField(default='', help_text='抄送人邮箱'),
        ),
        migrations.AlterField(
            model_name='outsitemsg',
            name='send_to',
            field=models.TextField(default='', help_text='接收对象信息'),
        ),
    ]
