# Generated by Django 2.2 on 2021-12-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tone', '0004_auto_20211206_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='short_name',
            field=models.CharField(blank=True, help_text='Case简化名', max_length=255, null=True),
        ),
    ]
