# Generated by Django 2.2 on 2021-12-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tone', '0005_testcase_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='priority',
            field=models.IntegerField(default=10, help_text='显示优先级'),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.IntegerField(default=10, help_text='显示优先级'),
        ),
    ]
