# Generated by Django 2.2 on 2022-03-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tone', '0006_auto_20211213_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='drag_modified',
            field=models.DateTimeField(auto_now_add=True, help_text='拖拽修改时间', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='drag_modified',
            field=models.DateTimeField(auto_now_add=True, help_text='拖拽修改时间', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_show',
            field=models.BooleanField(default=False, help_text='是否统计dashboard'),
        ),
    ]
