# Generated by Django 2.2 on 2022-04-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tone', '0007_auto_20220310_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudserver',
            name='real_state',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Broken', 'Broken'), ('Reserved', 'Reserved'), ('Unusable', 'Unusable')], default='Available', help_text='真实状态', max_length=64),
        ),
        migrations.AlterField(
            model_name='cloudserver',
            name='state',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Broken', 'Broken'), ('Reserved', 'Reserved'), ('Unusable', 'Unusable')], default='Available', help_text='状态', max_length=64),
        ),
        migrations.AlterField(
            model_name='cloudserversnapshot',
            name='real_state',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Broken', 'Broken'), ('Reserved', 'Reserved'), ('Unusable', 'Unusable')], default='Available', help_text='真实状态', max_length=64),
        ),
        migrations.AlterField(
            model_name='cloudserversnapshot',
            name='state',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Broken', 'Broken'), ('Reserved', 'Reserved'), ('Unusable', 'Unusable')], default='Available', help_text='状态', max_length=64),
        ),
        migrations.AlterField(
            model_name='testjob',
            name='note',
            field=models.TextField(blank=True, help_text='NOTE', null=True),
        ),
        migrations.AlterField(
            model_name='testserver',
            name='real_state',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Broken', 'Broken'), ('Reserved', 'Reserved'), ('Unusable', 'Unusable')], default='Available', help_text='真实状态', max_length=64),
        ),
        migrations.AlterField(
            model_name='testserver',
            name='state',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Broken', 'Broken'), ('Reserved', 'Reserved'), ('Unusable', 'Unusable')], default='Available', help_text='状态', max_length=64),
        ),
        migrations.AlterField(
            model_name='testserversnapshot',
            name='real_state',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Broken', 'Broken'), ('Reserved', 'Reserved'), ('Unusable', 'Unusable')], default='Available', help_text='真实状态', max_length=64),
        ),
        migrations.AlterField(
            model_name='testserversnapshot',
            name='state',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Broken', 'Broken'), ('Reserved', 'Reserved'), ('Unusable', 'Unusable')], default='Available', help_text='状态', max_length=64),
        ),
    ]
