# Generated by Django 2.2 on 2022-06-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tone', '0008_auto_20220402_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='testjob',
            name='baseline_job_id',
            field=models.IntegerField(blank=True, help_text='基线Job', null=True),
        ),
        migrations.AddField(
            model_name='testtemplate',
            name='baseline_job_id',
            field=models.IntegerField(blank=True, help_text='基线Job', null=True),
        ),
    ]
