# Generated by Django 3.2.5 on 2022-06-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tone', '0009_auto_20220602_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudak',
            name='vm_quota',
            field=models.CharField(default='*', help_text='创建VM限额', max_length=8),
        ),
        migrations.AddField(
            model_name='cloudserver',
            name='history_state',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Broken', 'Broken'), ('Reserved', 'Reserved'), ('Unusable', 'Unusable')], default='Available', help_text='历史状态', max_length=64),
        ),
        migrations.AddField(
            model_name='cloudserversnapshot',
            name='history_state',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Broken', 'Broken'), ('Reserved', 'Reserved'), ('Unusable', 'Unusable')], default='Available', help_text='历史状态', max_length=64),
        ),
        migrations.AddField(
            model_name='testserver',
            name='history_state',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Broken', 'Broken'), ('Reserved', 'Reserved'), ('Unusable', 'Unusable')], default='Available', help_text='历史状态', max_length=64),
        ),
        migrations.AddField(
            model_name='testserversnapshot',
            name='history_state',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Broken', 'Broken'), ('Reserved', 'Reserved'), ('Unusable', 'Unusable')], default='Available', help_text='历史状态', max_length=64),
        ),
    ]
