# Generated by Django 2.2 on 2022-07-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tone', '0010_auto_20220615_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudserver',
            name='tsn',
            field=models.CharField(help_text='TSN', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='cloudserversnapshot',
            name='tsn',
            field=models.CharField(help_text='TSN', max_length=64, null=True),
        ),
    ]
