# Generated by Django 2.2 on 2022-06-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tone', '0010_auto_20220615_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
