# Generated by Django 2.2 on 2022-07-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tone', '0011_user_avatar'),
        ('tone', '0011_auto_20220706_1426'),
    ]

    operations = [
    ]
