# Generated by Django 2.2 on 2022-07-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tone', '0012_merge_20220707_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testjobcase',
            name='job_id',
            field=models.IntegerField(db_index=True, help_text='关联JOB ID'),
        ),
    ]
