# Generated by Django 2.2 on 2022-07-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tone', '0013_auto_20220719_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudserversnapshot',
            name='gcc',
            field=models.TextField(help_text='gcc版本', null=True),
        ),
        migrations.AlterField(
            model_name='testserversnapshot',
            name='gcc',
            field=models.TextField(help_text='gcc版本', null=True),
        ),
    ]
