# Generated by Django 2.2 on 2022-08-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tone', '0014_auto_20220729_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testjob',
            name='product_version',
            field=models.TextField(blank=True, help_text='product_version', null=True),
        ),
    ]
