# Generated by Django 3.2.13 on 2022-08-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tone', '0014_auto_20220720_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testjob',
            name='product_version',
            field=models.TextField(blank=True, help_text='product_version', null=True),
        )
    ]
