# Generated by Django 3.2.5 on 2022-08-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tone', '0015_auto_20220812_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='background_desc',
            field=models.CharField(blank=True, help_text='测试背景描述', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='env_description_desc',
            field=models.CharField(blank=True, help_text='测试环境描述', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='test_conclusion_desc',
            field=models.CharField(blank=True, help_text='测试结论描述', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='test_env_desc',
            field=models.CharField(blank=True, help_text='机器环境描述', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='test_method_desc',
            field=models.CharField(blank=True, help_text='测试方法描述', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='test_summary_desc',
            field=models.CharField(blank=True, help_text='测试总结描述', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='reporttmplitemsuite',
            name='test_conclusion_desc',
            field=models.CharField(blank=True, help_text='测试结论描述', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='reporttmplitemsuite',
            name='test_description_desc',
            field=models.CharField(blank=True, help_text='测试说明描述', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='reporttmplitemsuite',
            name='test_env_desc',
            field=models.CharField(blank=True, help_text='测试环境描述', max_length=128, null=True),
        ),
    ]
