# Generated by Django 3.2.5 on 2022-11-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tone', '0018_auto_20221020_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_cluster',
            name='is_instance',
            field=models.BooleanField(default=True, help_text='是否实例'),
        )
    ]
