# Generated by Django 2.2 on 2022-12-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tone', '0018_auto_20221020_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseServerRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='create_at')),
                ('gmt_modified', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='modify_at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否被删除')),
                ('server_id', models.IntegerField(help_text='机器ID', unique=True)),
                ('server_instance_id', models.CharField(help_text='机器实例ID', max_length=128)),
                ('estimated_release_at', models.DateTimeField(help_text='预计释放时间')),
                ('is_release', models.BooleanField(default=False, help_text='是否已释放')),
                ('release_at', models.DateTimeField(help_text='释放时间')),
            ],
            options={
                'db_table': 'release_server_record',
            },
        ),
        migrations.AddField(
            model_name='testcluster',
            name='is_instance',
            field=models.BooleanField(default=True, help_text='是否实例'),
        ),
        migrations.AlterField(
            model_name='cloudserver',
            name='channel_type',
            field=models.CharField(choices=[('otheragent', 'otheragent'), ('toneagent', 'toneagent')], default='toneagent', help_text='通道类型', max_length=64),
        ),
        migrations.AlterField(
            model_name='cloudserver',
            name='instance_id',
            field=models.CharField(db_index=True, help_text='Instance id', max_length=64),
        ),
        migrations.AlterField(
            model_name='cloudserver',
            name='release_rule',
            field=models.IntegerField(choices=[(0, '用完不释放'), (1, '用完释放'), (2, '有失败用例时不释放（保留24小时）')], default=1, help_text='用完释放'),
        ),
        migrations.AlterField(
            model_name='cloudserversnapshot',
            name='channel_type',
            field=models.CharField(choices=[('otheragent', 'otheragent'), ('toneagent', 'toneagent')], default='toneagent', help_text='通道类型', max_length=64),
        ),
        migrations.AlterField(
            model_name='cloudserversnapshot',
            name='instance_id',
            field=models.CharField(blank=True, db_index=True, help_text='Instance id', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='cloudserversnapshot',
            name='release_rule',
            field=models.IntegerField(choices=[(0, '用完不释放'), (1, '用完释放'), (2, '有失败用例时不释放（保留24小时）')], default=1, help_text='用完释放'),
        ),
        migrations.AlterField(
            model_name='planinstancepreparerelation',
            name='channel_type',
            field=models.CharField(blank=True, choices=[('otheragent', 'otheragent'), ('toneagent', 'toneagent')], default='otheragent', help_text='通道类型', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='testserver',
            name='channel_type',
            field=models.CharField(choices=[('otheragent', 'otheragent'), ('toneagent', 'toneagent')], help_text='通道类型', max_length=64),
        ),
        migrations.AlterField(
            model_name='testserversnapshot',
            name='channel_type',
            field=models.CharField(choices=[('otheragent', 'otheragent'), ('toneagent', 'toneagent')], help_text='通道类型', max_length=64),
        ),
    ]
