# Generated by Django 3.2.5 on 2023-01-06 14:48
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tone', '0020_auto_20221223_1708'),
    ]
    operations = [
        migrations.AlterField(
            model_name='baseline',
            name='server_provider',
            field=models.CharField(choices=[('aligroup', '集团内'), ('aliyun', '阿里云')], default='aligroup', help_text='机器类型', max_length=64, null=True),
        ),
    ]