# Generated by Django 3.2.17 on 2023-02-17 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tone', '0021_auto_20230106_1603'),
        ('tone', '0021_auto_20230203_1426'),
    ]

    operations = [
    ]
