JOB_TYPE_ITEM_DATA = [
    {'name': 'job_name', 'show_name': 'Job名称',
     'description': '自定义Job名称', 'config_index': 1},
    {'name': 'project', 'show_name': 'Project选择',
     'description': '选择Job所属project', 'config_index': 1},
    {'name': 'baseline', 'show_name': '测试基线',
     'description': '选择与Job对比的基线', 'config_index': 1},

    {'name': 'kernel_install', 'show_name': '重装内核',
     'description': '安装发布、未发布、build内核等信息', 'config_index': 2},
    {'name': 'reboot', 'show_name': '重启机器',
     'description': '针对机器是否重启的操作', 'config_index': 2},
    {'name': 'global_variable', 'show_name': '全局变量',
     'description': 'Job的全局变量配置', 'config_index': 2},
    {'name': 'rpm', 'show_name': 'RPM列表',
     'description': '安装rpm和选择安装时间配置', 'config_index': 2},
    {'name': 'script', 'show_name': '执行脚本',
     'description': '安装脚本和选择安装的时间配置', 'config_index': 2},

    {'name': 'domain', 'show_name': '领域选择',
     'description': '开启按领域分类选择', 'config_index': 3},
    {'name': 'variable', 'show_name': '变量',
     'description': '用例的变量值', 'config_index': 3},
    {'name': 'reboot', 'show_name': '重启',
     'description': '是否开启重启功能', 'config_index': 3},
    {'name': 'script', 'show_name': '脚本',
     'description': '是否开启脚本功能', 'config_index': 3},

    {'name': 'cleanup', 'show_name': '清理脚本',
     'description': '任务结束后，清理测试机', 'config_index': 4},
    {'name': 'notice_subject', 'show_name': '通知主题',
     'description': '订阅通知主题', 'config_index': 4},
    {'name': 'ding_notice', 'show_name': '钉钉通知',
     'description': '订阅钉钉通知消息', 'config_index': 4},
    {'name': 'email_notice', 'show_name': '邮件通知',
     'description': '订阅邮件通知消息', 'config_index': 4},
    {'name': 'job_tag', 'show_name': 'Job标签',
     'description': '自定义Job标签，可按标签分类选择', 'config_index': 4},
    {'name': 'report', 'show_name': '自动生成报告',
     'description': '自动生成Job测试报告', 'config_index': 4},
    {'name': 'callback_api', 'show_name': '回调接口',
     'description': '配置回调接口', 'config_index': 4},
]

JOB_TYPE_TMPL_DATA = [
    {
        'name': '功能测试',
        'test_type': 'functional',
        'server_type': 'aligroup',
        'enable': True,
        'priority': 1,
        'description': '',
        'items': [
            ('job_name', 1),
            ('project', 1),
            ('baseline', 1),
            ('global_variable', 2),
            ('kernel_install', 2),
            ('reboot', 2),
            ('rpm', 2),
            ('script', 2),
            ('domain', 3),
            ('variable', 3),
            ('reboot', 3),
            ('script', 3),
            ('cleanup', 4),
            ('notice_subject', 4),
            ('ding_notice', 4),
            ('email_notice', 4),
            ('job_tag', 4),
            ('report', 4),
            ('callback_api', 4)
        ]
    },
    {
        'name': '性能测试',
        'test_type': 'performance',
        'server_type': 'aligroup',
        'enable': True,
        'priority': 2,
        'description': '',
        'items': [
            ('job_name', 1),
            ('project', 1),
            ('baseline', 1),
            ('global_variable', 2),
            ('kernel_install', 2),
            ('reboot', 2),
            ('rpm', 2),
            ('script', 2),
            ('domain', 3),
            ('variable', 3),
            ('reboot', 3),
            ('script', 3),
            ('cleanup', 4),
            ('notice_subject', 4),
            ('ding_notice', 4),
            ('email_notice', 4),
            ('job_tag', 4),
            ('report', 4),
            ('callback_api', 4)
        ]
    },
    {
        'name': '云上功能测试',
        'test_type': 'functional',
        'server_type': 'aliyun',
        'enable': True,
        'is_default': True,
        'is_first': True,
        'priority': 3,
        'description': '',
        'items': [
            ('job_name', 1),
            ('project', 1),
            ('baseline', 1),
            ('global_variable', 2),
            ('kernel_install', 2),
            ('reboot', 2),
            ('rpm', 2),
            ('script', 2),
            ('domain', 3),
            ('variable', 3),
            ('reboot', 3),
            ('script', 3),
            ('cleanup', 4),
            ('notice_subject', 4),
            ('ding_notice', 4),
            ('email_notice', 4),
            ('job_tag', 4),
        ]
    },
    {
        'name': '云上性能测试',
        'test_type': 'performance',
        'server_type': 'aliyun',
        'enable': True,
        'priority': 4,
        'description': '',
        'items': [
            ('job_name', 1),
            ('project', 1),
            ('baseline', 1),
            ('global_variable', 2),
            ('kernel_install', 2),
            ('reboot', 2),
            ('rpm', 2),
            ('script', 2),
            ('domain', 3),
            ('variable', 3),
            ('reboot', 3),
            ('script', 3),
            ('cleanup', 4),
            ('notice_subject', 4),
            ('ding_notice', 4),
            ('email_notice', 4),
            ('job_tag', 4),
        ]
    },
]
