from tone.settings.base_settings import *
from tone.settings.auth_settings import *
from tone.settings.db_settings import *
from tone.settings.drf_settings import *
from tone.settings.oss_settings import *
from tone.settings.api_settings import *
from tone.settings.toneagent_setting import *
from tone.settings.log_settings import *
from tone.settings.redis_settings import *
from tone.settings.operationlog_setting import *
from tone.settings.email_settings import *
from tone.settings.celery_settings import *
